minimumReleaseAgeExclude:
  - "@expo/cli@57.0.21"
  - "@expo/fingerprint@0.20.12"
  - "@expo/metro-runtime@57.0.15"
  - "@expo/router-server@57.0.9"
  - "@expo/ui@57.0.15"
  - babel-preset-expo@57.0.10
  - expo-asset@57.0.16
  - expo-constants@57.0.17
  - expo-font@57.0.3
  - expo-image@57.0.4
  - expo-linking@57.0.9
  - expo-modules-core@57.0.15
  - expo-modules-jsi@57.0.7
  - expo-router@57.0.18
  - expo@57.0.19
nodeLinker: hoisted
